apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
  name: first-pipeline-demo
  namespace: openshift-pipelines
spec:

### These are all the parameters used by the various Tasks in this pipeline

  params:

### parameters for Task zero
    - name: sourceImage
      description: The container image that we are checking for a signature
      type: string
      default: registry.redhat.io/ubi9/ubi:9.5-1739751568

    - name: publicKey
      description: name of the secret holding the public key used by cosign cli
      type: string
      default: cosign-public-key

### parameters for Task one (this task also reuses the sourceImage parameter from Task Zero)
    - name: sbomDestination
      description: destination of where to upload the SBOM (Typically in the same location as the container image)
      type: string

### parameters for Task two
    - name: github-repo-revision
      default: main
      description: Git branch
      type: string

    - name: github-repo-url
      default: 'https://github.com/SimonDelord/chains-pipeline.git'
      description: Github repo
      type: string

    - name: context-dir
      type: string
      default: '/'

### parameters for Task three

    - name: destinationImage
      description: Destination of the container image to be uploaded.
      type: string


### This is now the lists of Tasks for the Pipeline

  tasks:
### Task Zero - Check that the Red Hat UBI sitting in the local Container Rego is signed
    - name: check-redhat-ubi-is-signed
      params:
        - name: sourceImage
          value: $(params.sourceImage)
        - name: publicKey
          value: $(params.publicKey)
      taskRef:
        kind: Task
        name: check-redhat-ubi-is-signed

### Task One - Provide the SBOM and Uploads it to the local Container Image Repo

## No longer needed.

### Task Two - clone the Git Source Repo so the UBI image can be built
    - name: clone-sources
      params:
        - name: URL
          value: $(params.github-repo-url)
        - name: revision
          value: $(params.github-repo-revision)
        - name: deleteExisting
          value: 'true'
      runAfter:
        - check-redhat-ubi-is-signed
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: source

### Task Three - build the image and upload to the right location (if using tekton, and tekton chains, the image will be automatically signed)

    - name: build-and-push-image
      params:
        - name: IMAGE
          value: $(params.destinationImage)

        - name: CONTEXT
          value: .

      runAfter:
        - clone-sources
      taskRef:
        kind: Task
        name: harden-ubi-build
      workspaces:
        - name: source
          workspace: source

  workspaces:
    - name: source
