apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: generate-sbom-and-upload-to-repo-
  namespace: openshift-pipelines
  labels:
    app.kubernetes.io/managed-by: tekton-pipelines
    app.kubernetes.io/version: '0.1'
    tekton.dev/task: syft
spec:
  params:
    - name: sourceImage
      value: "example-registry-quay-quay.apps.rosa-pwfrp.lnqt.p1.openshiftapps.com/quayuser1/demo:v.9.6"
    - name: destination
      value: "example-registry-quay-quay.apps.rosa-pwfrp.lnqt.p1.openshiftapps.com/quayuser1/final-demo:v.9.7"
  serviceAccountName: pipeline
  taskRef:
    kind: Task
    name: generate-sbom-and-upload-to-repo
  timeout: 1h0m0s
