apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: react-scan-pipelinerun
  labels:
    tekton.dev/pipeline: build-scan-and-deploy
spec:
  params:
    - name: github-repo-revision
      value: main
    - name: github-repo-url
      value: 'https://github.com/shaneboulden/chains-pipeline.git'
    - name: context-dir
      value: /
    - name: image
      value: 'example-registry-quay-quay.apps.rosa-pwfrp.lnqt.p1.openshiftapps.com/quayuser1/demo:v.9.8'
  pipelineRef:
    name: build-scan-and-deploy
  taskRunTemplate:
    podTemplate:
      securityContext:
        fsGroup: 0
        runAsUser: 0
      volumes:
        - name: varlibcontainers
          persistentVolumeClaim:
            claimName: containers-pvc
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: pipeline-pvc
