apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-clone-simon
spec:
  params:
    - name: github-repo-revision
      type: string
      description: Git branch
      default: main
    - name: github-repo-url
      type: string
      description: Github repo
      default: https://github.com/shaneboulden/chains-pipeline.git
    - name: context-dir
      type: string
  workspaces:
    - name: source
  tasks:
  - name: clone-sources
    taskRef:
      name: git-clone
      kind: Task
    params:
      - name: URL
        value: '$(params.github-repo-url)'
      - name: revision
        value: '$(params.github-repo-revision)'
      - name: deleteExisting
        value: 'true'
    workspaces:
      - name: output
        workspace: source
