#FROM registry.access.redhat.com/ubi8/ubi-minimal

FROM example-registry-quay-quay.apps.rosa-mqc4s.nkv5.p1.openshiftapps.com/quayuser1/ubitest:v.9.5

#RUN \
#  microdnf install \
#  net-tools bind-utils iputils curl git unzip vim wget \
#  && microdnf clean all

ENV HOME /root

WORKDIR /root

CMD tail -f /dev/null
