FROM docker.io/anchore/syft:v0.35.1@sha256:fd2da1424585680f220ed61db13096f7abcd0c0073b52616bbce397a8e708a96
ENV HOME /root

WORKDIR /root


RUN ["/bin/sh", "-c", "echo I am using bash"]
##CMD ls
 ##- "/bin/bash"
  ##        - "-c"
   ##       - "--"
    ##    args: 
     ##     - "while true; do sleep 30; done;"
