apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-sbom-and-upload-to-repo
spec:
  params:
    - description: the container registry for the container image for which the sbom is generated
      name: sourceImage
      type: string
    - description: the registry where the sbom is going to be uploaded
      name: destination
      type: string
  steps:
    - computeResources: {}
      image: quay.io/rhn_support_sdelord/magic-image
      name: use-syft-for-sbom
      script: |
        curl https://raw.githubusercontent.com/SimonDelord/UBI-Security/refs/heads/main/bastion-build/syft-build/.syft.yaml >> .syft.yaml; syft "$(params.sourceImage)" >> simon.spdx.sbom; ./go/bin/cosign upload blob -f simon.spdx.sbom "$(params.destination)" --allow-insecure-registry=true --registry-username=quayuser1 --registry-password=1800redhat
