apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: second-pipeline-demo-
  annotations:
    chains.tekton.dev/signed: 'true'
    chains.tekton.dev/transparency: 'https://rekor-server-trusted-artifact-signer.apps.rosa-pwfrp.lnqt.p1.openshiftapps.com//api/v1/log/entries?logIndex=36'
    results.tekton.dev/stored: 'true'
  generation: 1
  namespace: openshift-pipelines
  labels:
    tekton.dev/pipeline: second-pipeline-demo
spec:
  params:

### Task one
    - name: sourceImage
      value: example-registry-quay-quay.apps.rosa-pwfrp.lnqt.p1.openshiftapps.com/quayuser1/ubi-base-customer:v.9.6

    - name: github-repo-revision
      value: main

    - name: github-repo-url
      value: 'https://github.com/SimonDelord/hardened-ubi-demo.git'

    - name: context-dir
      value: /hardened/

### Task two
    - name: destinationImage
      value: example-registry-quay-quay.apps.rosa-pwfrp.lnqt.p1.openshiftapps.com/quayuser1/ubi-hardened-demo:v.9.6


### Task three
    - name: sbomDestination
      value: example-registry-quay-quay.apps.rosa-pwfrp.lnqt.p1.openshiftapps.com/quayuser1/ubi-hardened-demo:v.9.6.sbom


  pipelineRef:
    name: second-pipeline-demo
  taskRunTemplate:
    podTemplate:
      securityContext:
        fsGroup: 0
        runAsUser: 0
      volumes:
        - name: varlibcontainers
          persistentVolumeClaim:
            claimName: containers-pvc-2
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: pipeline-pvc-2
