apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  annotations:
  name: second-pipeline-demo
  namespace: openshift-pipelines
spec:

### These are all the parameters used by the various Tasks in this pipeline

  params:

### parameters for Task one

    - name: sourceImage
      description: The container image that we are hardening
      type: string

    - name: github-repo-revision
      default: main
      description: Git branch
      type: string

    - name: github-repo-url
      default: 'https://github.com/shaneboulden/chains-pipeline.git'
      description: Github repo
      type: string

    - name: context-dir
      type: string

### parameters for Task two

    - name: destinationImage
      description: Destination of the container image to be uploaded.
      type: string

### parameters for Task three (this task also reuses the sourceImage parameter from Task Zero)
    - name: sbomDestination
      description: destination of where to upload the SBOM (Typically in the same location as the container image)
      type: string

    - name: publicKey
      description: name of the secret holding the public key used by cosign cli
      type: string
      default: cosign-public-key

### parameters for Task Four
   - name: imageToSign 
     description: name of the image to sign and location
     type: string
     default: example-registry-quay-quay.apps.rosa-pwfrp.lnqt.p1.openshiftapps.com/quayuser1/ubi-hardened-demo:v.9.6
     
   - name: rekor-url
     description: url for the rekor server
     type: string
     default: https://rekor-server-trusted-artifact-signer.apps.rosa-pwfrp.lnqt.p1.openshiftapps.com/
    
   - name: otherPublicKey
     description: name of the k8s secret holding the key pair for cosign to use
     type: string
     default: signing-secrets

### This is now the lists of Tasks for the Pipeline

  tasks:

### Task One - clone the Git Source Repo so the hardened UBI image can be built
    - name: clone-sources
      params:
        - name: URL
          value: $(params.github-repo-url)
        - name: revision
          value: $(params.github-repo-revision)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: source

### Task Two - build the image and upload to the right location (if using tekton, and tekton chains, the image will be automatically signed)

    - name: build-and-push-image
      params:
        - name: IMAGE
          value: $(params.destinationImage)

        - name: CONTEXT
          value: .

      runAfter:
        - clone-sources
      taskRef:
        kind: Task
        name: harden-ubi-build
      workspaces:
        - name: source
          workspace: source

### Task three - Provide the SBOM and Uploads it to the local Container Image Repo

    - name: generate-sbom-and-upload-to-repo
      params:
        - name: sourceImage
          value: $(params.sourceImage)
        - name: destination
          value: $(params.sbomDestination)
      taskRef:
        kind: Task
        name: generate-sbom-and-upload-to-repo
      runAfter:
        - build-and-push-image

### Task four - Sign the image using the magic image and the cosign cli

    - name: cosign-sign-image
      params:
        - name: sourceImage 
          value: $(params.imageToSign)
        - name: rekor-url
          value: $(params.rekor-url)
        - name: publicKey
          value: $(params.otherPublicKey)
      taskRef:
        kind: Task
        name: cosign-sign-image
      runAfter:
        - generate-sbom-and-upload-to-repo
        


  workspaces:
    - name: source
